test branch

diff --git a/.github/workflows/link-ticket.yml b/.github/workflows/link-ticket.yml
--- a/.github/workflows/link-ticket.yml
+++ b/.github/workflows/link-ticket.yml
@@ -26,7 +26,7 @@ jobs:
   capture-ticket-id:
     runs-on: ubuntu-latest
     outputs:
-      card_id: ${{ steps.extract-card-id.outputs.card_id }}
+      ticket_id: ${{ steps.extract-ticket-id.outputs.ticket_id }}
       skip: ${{ steps.check-comment.outputs.skip }}
     steps:
       - name: Checkout code
@@ -40,6 +40,7 @@ jobs:
           if [[ -n "$COMMENT_FOUND" ]]; then
             echo "Found Linked Ticket Comment. Skipping job."
             echo "::set-output name=skip::true"
+            exit 0
           else
             echo "::set-output name=skip::false"
           fi          
@@ -49,32 +50,34 @@ jobs:
           ENCODED_BODY=$(echo "${{ inputs.pullRequestBody }}" | base64 -w 0)
           echo "ENCODED_BODY=$ENCODED_BODY" >> $GITHUB_ENV
 
-      - name: Extract Trello Card ID from Branch Name or PR Body
-        id: extract-card-id
+      - name: Extract Ticket ID from Branch Name or PR Body
+        id: extract-ticket-id
         run: |
           BRANCH_NAME="${{ inputs.headRef }}"
           PR_BODY=$(echo "$ENCODED_BODY" | base64 --decode)
           # Using regex to extract card ID that starts with 'task_' followed by alphanumeric characters
-          TRELLO_CARD_ID=$(echo "$BRANCH_NAME" | grep -oP '(?i:task)_\K[A-Za-z0-9]+' || echo "$PR_BODY" | grep -oP '(?i:task)_\K[A-Za-z0-9]+' || echo "")
-          if [[ -z "$TRELLO_CARD_ID" ]]; then
-            echo "No card ID found in branch name or PR body."
+          TRELLO_TICKET_ID=$(echo "$BRANCH_NAME" | grep -oP '(?i:task)_\K[A-Za-z0-9]+' || echo "$PR_BODY" | grep -oP '(?i:task)_\K[A-Za-z0-9]+' || echo "")
+          if [[ -z "$TRELLO_TICKET_ID" ]]; then
+            echo "No ticket ID found in branch name or PR body."
+            exit 1
           else
-            echo "Found Card ID: $TRELLO_CARD_ID"
-            echo "::set-output name=card_id::$TRELLO_CARD_ID"
+            echo "Found Ticket ID: $TRELLO_TICKET_ID"
+            echo "::set-output name=skip::false"
+            echo "::set-output name=ticket_id::$TRELLO_TICKET_ID"
           fi
 
   link-ticket:
     needs: capture-ticket-id
-    if: ${{ !needs.capture-ticket-id.outputs.skip }}
+    if: ${{ needs.capture-ticket-id.outputs.skip == 'false' }}
     runs-on: ubuntu-latest
     steps:
       - name: Link PR and Trello Ticket
         run: |
-          TRELLO_CARD_ID="${{ needs.capture-ticket-id.outputs.card_id }}"
-          TRELLO_CARD_URL="https://trello.com/c/$TRELLO_CARD_ID"
+          TRELLO_TICKET_ID="${{ needs.capture-ticket-id.outputs.ticket_id }}"
+          TRELLO_CARD_URL="https://trello.com/c/$TRELLO_TICKET_ID"
           PR_URL="${{ inputs.pullRequestHtmlUrl }}"
 
-          TRELLO_RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "https://api.trello.com/1/cards/$TRELLO_CARD_ID/attachments" \
+          TRELLO_RESPONSE=$(curl -s -o response.json -w "%{http_code}" -X POST "https://api.trello.com/1/cards/$TRELLO_TICKET_ID/attachments" \
           -d "key=${{ secrets.TRELLO_API_KEY }}" \
           -d "token=${{ secrets.TRELLO_API_TOKEN }}" \
           -d "url=$PR_URL")
@@ -90,7 +93,17 @@ jobs:
           fi
             
           COMMENT_BODY="Linked Ticket: $TRELLO_CARD_URL"
-          curl -s -H "Authorization: token ${{ secrets.USER_GITHUB_TOKEN }}" \
-          -H "Accept: application/vnd.github.v3+json" \
-          -d "{\"body\": \"$COMMENT_BODY\"}" \
-          "https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.pullRequestNumber }}/comments"
+          RESPONSE=$(curl -s -o response-body.json -w "%{http_code}" -H "Authorization: token ${{ secrets.USER_GITHUB_TOKEN }}" \
+            -H "Accept: application/vnd.github.v3+json" \
+            -d "{\"body\": \"$COMMENT_BODY\"}" \
+            "https://api.github.com/repos/${{ github.repository }}/issues/${{ inputs.pullRequestNumber }}/comments")
+          echo "GitHub API Response Code: $RESPONSE"
+          cat response-body.json
+
+          if [[ "$RESPONSE" -ne 201 ]]; then
+            echo "Failed to post comment. Response code: $RESPONSE"
+            cat response-body.json
+            exit 1
+          else
+            echo "Comment successfully attached to PR."
+          fi
